/*----- PROTECTED REGION ID(PiLC_PICOLASClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PiLC_PICOLASClass.cpp
//
// description : C++ source for the PiLC_PICOLASClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the PiLC_PICOLAS once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PiLC_PICOLASClass.h>

/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass.cpp

//-------------------------------------------------------------------
/**
 *	Create PiLC_PICOLASClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_PiLC_PICOLAS_class(const char *name) {
		return PiLC_PICOLAS_ns::PiLC_PICOLASClass::init(name);
	}
}

namespace PiLC_PICOLAS_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
PiLC_PICOLASClass *PiLC_PICOLASClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		PiLC_PICOLASClass::PiLC_PICOLASClass(string &s)
 * description : 	constructor for the PiLC_PICOLASClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
PiLC_PICOLASClass::PiLC_PICOLASClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering PiLC_PICOLASClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::constructor

	cout2 << "Leaving PiLC_PICOLASClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		PiLC_PICOLASClass::~PiLC_PICOLASClass()
 * description : 	destructor for the PiLC_PICOLASClass
 */
//--------------------------------------------------------
PiLC_PICOLASClass::~PiLC_PICOLASClass()
{
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		PiLC_PICOLASClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
PiLC_PICOLASClass *PiLC_PICOLASClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new PiLC_PICOLASClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		PiLC_PICOLASClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
PiLC_PICOLASClass *PiLC_PICOLASClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================

//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum PiLC_PICOLASClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum PiLC_PICOLASClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum PiLC_PICOLASClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "PiLCDevice";
	prop_desc = "Name of the PiLC tango device to connect to";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Class to control PiLC for Strobe lighting");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new PiLC_PICOLAS(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		PiLC_PICOLAS *dev = static_cast<PiLC_PICOLAS *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::attribute_factory_before
	//	Attribute : External_Trigger_Active
	External_Trigger_ActiveAttrib	*external_trigger_active = new External_Trigger_ActiveAttrib();
	Tango::UserDefaultAttrProp	external_trigger_active_prop;
	external_trigger_active_prop.set_description("Incoming Signal 1, else 0.");
	external_trigger_active_prop.set_label("External_Trigger_Active");
	//	unit	not set for External_Trigger_Active
	//	standard_unit	not set for External_Trigger_Active
	//	display_unit	not set for External_Trigger_Active
	//	format	not set for External_Trigger_Active
	//	max_value	not set for External_Trigger_Active
	//	min_value	not set for External_Trigger_Active
	//	max_alarm	not set for External_Trigger_Active
	//	min_alarm	not set for External_Trigger_Active
	//	max_warning	not set for External_Trigger_Active
	//	min_warning	not set for External_Trigger_Active
	//	delta_t	not set for External_Trigger_Active
	//	delta_val	not set for External_Trigger_Active
	
	external_trigger_active->set_default_properties(external_trigger_active_prop);
	//	Not Polled
	external_trigger_active->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(external_trigger_active);

	//	Attribute : Frequency_divider
	Frequency_dividerAttrib	*frequency_divider = new Frequency_dividerAttrib();
	Tango::UserDefaultAttrProp	frequency_divider_prop;
	//	description	not set for Frequency_divider
	frequency_divider_prop.set_label("Frequency_divider");
	//	unit	not set for Frequency_divider
	//	standard_unit	not set for Frequency_divider
	//	display_unit	not set for Frequency_divider
	//	format	not set for Frequency_divider
	//	max_value	not set for Frequency_divider
	frequency_divider_prop.set_min_value("1");
	//	max_alarm	not set for Frequency_divider
	//	min_alarm	not set for Frequency_divider
	//	max_warning	not set for Frequency_divider
	//	min_warning	not set for Frequency_divider
	//	delta_t	not set for Frequency_divider
	//	delta_val	not set for Frequency_divider
	
	frequency_divider->set_default_properties(frequency_divider_prop);
	//	Not Polled
	frequency_divider->set_disp_level(Tango::OPERATOR);
	frequency_divider->set_memorized();
	frequency_divider->set_memorized_init(true);
	att_list.push_back(frequency_divider);

	//	Attribute : Delay
	DelayAttrib	*delay = new DelayAttrib();
	Tango::UserDefaultAttrProp	delay_prop;
	delay_prop.set_description("Delay from the incoming signal to the output signal, ns");
	delay_prop.set_label("Delay");
	delay_prop.set_unit("ns");
	//	standard_unit	not set for Delay
	//	display_unit	not set for Delay
	//	format	not set for Delay
	//	max_value	not set for Delay
	delay_prop.set_min_value("20");
	//	max_alarm	not set for Delay
	//	min_alarm	not set for Delay
	//	max_warning	not set for Delay
	//	min_warning	not set for Delay
	//	delta_t	not set for Delay
	//	delta_val	not set for Delay
	
	delay->set_default_properties(delay_prop);
	//	Not Polled
	delay->set_disp_level(Tango::OPERATOR);
	delay->set_memorized();
	delay->set_memorized_init(true);
	att_list.push_back(delay);

	//	Attribute : High_time
	High_timeAttrib	*high_time = new High_timeAttrib();
	Tango::UserDefaultAttrProp	high_time_prop;
	high_time_prop.set_description("High Time from the Output Signal, ns");
	high_time_prop.set_label("High_time");
	high_time_prop.set_unit("ns");
	//	standard_unit	not set for High_time
	//	display_unit	not set for High_time
	//	format	not set for High_time
	//	max_value	not set for High_time
	high_time_prop.set_min_value("20");
	//	max_alarm	not set for High_time
	//	min_alarm	not set for High_time
	//	max_warning	not set for High_time
	//	min_warning	not set for High_time
	//	delta_t	not set for High_time
	//	delta_val	not set for High_time
	
	high_time->set_default_properties(high_time_prop);
	//	Not Polled
	high_time->set_disp_level(Tango::OPERATOR);
	high_time->set_memorized();
	high_time->set_memorized_init(true);
	att_list.push_back(high_time);

	//	Attribute : Internal_Generator_Enable
	Internal_Generator_EnableAttrib	*internal_generator_enable = new Internal_Generator_EnableAttrib();
	Tango::UserDefaultAttrProp	internal_generator_enable_prop;
	internal_generator_enable_prop.set_description("Internal Frequency generator. false = disable. true = enable");
	internal_generator_enable_prop.set_label("Internal_Generator_Enable");
	//	unit	not set for Internal_Generator_Enable
	//	standard_unit	not set for Internal_Generator_Enable
	//	display_unit	not set for Internal_Generator_Enable
	//	format	not set for Internal_Generator_Enable
	//	max_value	not set for Internal_Generator_Enable
	//	min_value	not set for Internal_Generator_Enable
	//	max_alarm	not set for Internal_Generator_Enable
	//	min_alarm	not set for Internal_Generator_Enable
	//	max_warning	not set for Internal_Generator_Enable
	//	min_warning	not set for Internal_Generator_Enable
	//	delta_t	not set for Internal_Generator_Enable
	//	delta_val	not set for Internal_Generator_Enable
	
	internal_generator_enable->set_default_properties(internal_generator_enable_prop);
	//	Not Polled
	internal_generator_enable->set_disp_level(Tango::OPERATOR);
	internal_generator_enable->set_memorized();
	internal_generator_enable->set_memorized_init(true);
	att_list.push_back(internal_generator_enable);

	//	Attribute : Internal_frequency
	Internal_frequencyAttrib	*internal_frequency = new Internal_frequencyAttrib();
	Tango::UserDefaultAttrProp	internal_frequency_prop;
	//	description	not set for Internal_frequency
	internal_frequency_prop.set_label("Internal_frequency");
	internal_frequency_prop.set_unit("Hz");
	//	standard_unit	not set for Internal_frequency
	//	display_unit	not set for Internal_frequency
	//	format	not set for Internal_frequency
	internal_frequency_prop.set_max_value("100000");
	internal_frequency_prop.set_min_value("0.1");
	//	max_alarm	not set for Internal_frequency
	//	min_alarm	not set for Internal_frequency
	//	max_warning	not set for Internal_frequency
	//	min_warning	not set for Internal_frequency
	//	delta_t	not set for Internal_frequency
	//	delta_val	not set for Internal_frequency
	
	internal_frequency->set_default_properties(internal_frequency_prop);
	//	Not Polled
	internal_frequency->set_disp_level(Tango::OPERATOR);
	internal_frequency->set_memorized();
	internal_frequency->set_memorized_init(true);
	att_list.push_back(internal_frequency);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::pipe_factory_before
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::command_factory()
{
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::command_factory_before


	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		PiLC_PICOLASClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		PiLC_PICOLASClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void PiLC_PICOLASClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		PiLC_PICOLAS *dev = static_cast<PiLC_PICOLAS *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(PiLC_PICOLASClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLASClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *PiLC_PICOLASClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(PiLC_PICOLASClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLASClass::Additional Methods
} //	namespace
