/*----- PROTECTED REGION ID(PiLC_PICOLASStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PiLC_PICOLASStateMachine.cpp
//
// description : State machine file for the PiLC_PICOLAS class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PiLC_PICOLAS.h>

/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::PiLC_PICOLASStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  


namespace PiLC_PICOLAS_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLAS::is_External_Trigger_Active_allowed()
 *	Description : Execution allowed for External_Trigger_Active attribute
 */
//--------------------------------------------------------
bool PiLC_PICOLAS::is_External_Trigger_Active_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PiLC_PICOLAS::External_Trigger_ActiveStateAllowed_READ) ENABLED START -----*/
		
		/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::External_Trigger_ActiveStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLAS::is_Frequency_divider_allowed()
 *	Description : Execution allowed for Frequency_divider attribute
 */
//--------------------------------------------------------
bool PiLC_PICOLAS::is_Frequency_divider_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PiLC_PICOLAS::Frequency_dividerStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::Frequency_dividerStateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLAS::is_Delay_allowed()
 *	Description : Execution allowed for Delay attribute
 */
//--------------------------------------------------------
bool PiLC_PICOLAS::is_Delay_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PiLC_PICOLAS::DelayStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::DelayStateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLAS::is_High_time_allowed()
 *	Description : Execution allowed for High_time attribute
 */
//--------------------------------------------------------
bool PiLC_PICOLAS::is_High_time_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PiLC_PICOLAS::High_timeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::High_timeStateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLAS::is_Internal_Generator_Enable_allowed()
 *	Description : Execution allowed for Internal_Generator_Enable attribute
 */
//--------------------------------------------------------
bool PiLC_PICOLAS::is_Internal_Generator_Enable_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PiLC_PICOLAS::Internal_Generator_EnableStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::Internal_Generator_EnableStateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PiLC_PICOLAS::is_Internal_frequency_allowed()
 *	Description : Execution allowed for Internal_frequency attribute
 */
//--------------------------------------------------------
bool PiLC_PICOLAS::is_Internal_frequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(PiLC_PICOLAS::Internal_frequencyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::Internal_frequencyStateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(PiLC_PICOLAS::PiLC_PICOLASStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PiLC_PICOLAS::PiLC_PICOLASStateAllowed.AdditionalMethods

}	//	End of namespace
